on:
  push:
    branches:
      - main
    paths:
      - 'bot/**'
  pull_request:
    branches:
      - main
    paths:
      - 'bot/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set timestamp
        run: echo "TS=$(date +%s)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: pip install -r bot/requirements.txt -t bot/

      - name: Zip bot folder
        run: cd bot && zip -r ../bot.zip . && cd ..
        # The above is equivalent to 3 commands:
        # run: cd bot
        # run: zip -r ../bot.zip .
        # run: cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 cp bot.zip ${{ secrets.SKINSBOT_S3_BUCKET_URI }}bot/bot_${{env.TS}}.zip

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file bot/infra/template.yaml \
            --stack-name skinsbot-bot \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-execute-changeset  \
            --parameter-overrides TS=${{env.TS}} MYS3BUCKETNAME=${{ vars.MYS3BUCKETNAME }}